FROM n8nio/n8n:latest
ENV GENERIC_TIMEZONE=Asia/Calcutta
ENV TZ=Asia/Calcutta
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV N8N_RUNNERS_ENABLED=true
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=yourStrongPassword
